### ISSUE TITLE
screen shrink after each reboot

### ISSUE THREAD

**Issue by MrNHQ** [viktorgino/headunit-desktop#21] opened 2018-01-04 22:26 UTC
Hello,

I am using a 7inch hdmi screen 800x480 and i am using your image.
I added a auto login and auto start your headunit-app after boot.
Each time that the Pi boots, (screen for booting is ok) the app restart and the screen schrinks more and more. At the end I don't see the scren at all (please see attached pictures).

I have the same behavior without touching the image at all.

Would you know why? I shut it down by direcly powering off, is it a problem? 

![img_20180104_230300](https://user-images.githubusercontent.com/33041186/34586742-9544d548-f1a5-11e7-8cdb-9577cc35ca18.jpg)
![img_20180104_221204](https://user-images.githubusercontent.com/33041186/34586743-95609f12-f1a5-11e7-996c-d40979ed021f.jpg)
![img_20180104_230748](https://user-images.githubusercontent.com/33041186/34586744-9581ac02-f1a5-11e7-928a-f29f6ba5bb6c.jpg)

**Comment by mrsylerpowers** [comment] 2018-01-05 03:20
I had the same problem but instead of 'every time it rebooted' it was everytime I restarted the program.

**Comment by denghauser** [comment] 2018-01-10 18:43
I found the reason why, but can't solve the issue as I'm not deep enough in the code and can't find the place where it save the data.
There is a file named "/root/.config/viktorgino/viktorgino's HeadUnit Desktop.conf"
In this file there the current config is stored. And it seems that the (screen width - width of menu) is stored back into the General -> width variable.
So I found the reason but not the cure :-)
Maybe someone can help out here.

**Comment by viktorgino** [comment] 2018-01-12 11:49
It's caused by https://github.com/viktorgino/headunit-gui/blob/master/qml/main.qml#L12
I'll do a pull request shortly, and upload a new image that has this change this weekend.

**Comment by gomme600** [comment] 2018-01-28 11:07
I'm having the same problem, was anyone able to resolve it?

**Comment by viktorgino** [comment] 2018-03-02 18:18
Hi

This has been resolved with https://github.com/viktorgino/headunit-gui/commit/17700e1b92926a564dcfb3cb823b0957e9b9fe67

**Closed as completed by viktorgino** 2018-03-02 18:18 UTC
